version: '3.7'
services:
    app:
        container_name: react
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
        environment: 
            - CHOKIDAR_USEPOLLING=true
        ports:
            - '3000:8080'
            - "35729:35729"
    